### PR TITLE
refactor: rename internal references from Broadcaster to Gateway

### PR DESCRIPTION
**Pull request by rickstaa**
**What does this pull request do? Explain your changes. (required)**

This pull request updates internal references from 'Broadcaster' to 'Gateway' in accordance with the core team’s decision. For more details, refer to the discussion: [Discord
Link](https://discord.com/channels/423160867534929930/1051963444598943784/1210356864643109004).

It follows up on https://github.com/livepeer/go-livepeer/pull/3056 as I noticed I forgot to rename some references.

**Specific updates (required)**

- Renames some internal references of Broadcaster to Gateway in the `livepeer.go` and `starter.go` files.

**How did you test each of these updates (required)**

I checked the tests were successful and started a off-chain orchestrator and gateway.

**Does this pull request close any open issues?**

NO

**Checklist:**

- [x] Read the [contribution guide](./CONTRIBUTING.md)
- [x] `make` runs successfully
- [x] All tests in `./test.sh` pass
- [x] README and other documentation updated
- [ ] [Pending changelog](./CHANGELOG_PENDING.md) updated

### CODE REVIEW

**Comment by rickstaa** [comment]
@victorges I noticed in https://github.com/livepeer/go-livepeer/pull/2981 hat you added the following line:

https://github.com/livepeer/go-livepeer/blob/b739f354ce42d20d51c0778156999932dd8c2ae8/cmd/livepeer/starter/starter.go#L796

Since there's no goroutine or defer statement inside the loop that could cause a closure over the loop variable, we can safely remove the `p := p` line I think.

**Comment by victorges** [comment]
Hey @rickstaa!
Even tho there's no explicit go or defer statements there, there is a closure on this anonymous function sent to that auto updater: https://github.com/livepeer/go-livepeer/blob/b739f354ce42d20d51c0778156999932dd8c2ae8/cmd%2Flivepeer%2Fstarter%2Fstarter.go#L799

And that updater itself might start a goroutine that eventually runs that function. 

Do you think this could be made clear in some way?

**Comment by rickstaa** [comment]
> Hey @rickstaa! Even tho there's no explicit go or defer statements there, there is a closure on this anonymous function sent to that auto updater:
> 
> https://github.com/livepeer/go-livepeer/blob/b739f354ce42d20d51c0778156999932dd8c2ae8/cmd%2Flivepeer%2Fstarter%2Fstarter.go#L799
> 
> And that updater itself might start a goroutine that eventually runs that function.
> 
> Do you think this could be made clear in some way?

@victorges Ah, I think I had been programming for too long when I asked that question and overlooked the anonymous function 🤦🏻. Thanks for your explanation! I think in that case we are good to merge this 👍🏻.

**Review by victorges — APPROVED** [review]
LGTM

**Pull request merged**
