### PR TITLE
Copy audio streams

### PR DESCRIPTION
**Pull request by j0sh**
**What does this pull request do? Explain your changes. (required)**

Converts go-livepeer to use stream copy for audio, rather than transcoding audio to AAC.

* This allows us to verify audio for Streamflow, which can be bitexact.
* Sidesteps an issue with the LPMS transcoder producing a clicking sound : https://github.com/livepeer/lpms/issues/152

**Specific updates (required)**

- https://github.com/livepeer/go-livepeer/pull/1073/commits/59a9c112369c6a2f574443dfca405feb25116030 mod: Update LPMS to livepeer/lpms@7f095b3
- https://github.com/livepeer/go-livepeer/pull/1073/commits/7df3e331e47c4e822a4997982551ea194fc94349 mod: go mod tidy
- https://github.com/livepeer/go-livepeer/pull/1073/commits/f5259456cbe2d1bd4f7be33fd10894dd1ef33587 core: Stream copy audio rather than transcoding.

**How did you test each of these updates (required)**
* Added unit tests, including tests for bitexactness
* Manual testing. Visually verified that the spectrogram of transcoded audio is smooth.

* Unit tests pass within `core` but didn't run the full test suite because of https://github.com/livepeer/go-livepeer/issues/1072

```
I0905 01:36:10.751574    1718 ot_rpc.go:137] Transcoding taskId=742 url=linktomanifest
```

**Does this pull request close any open issues?**

**Checklist:**

- [ ] ~~README and other documentation updated~~
- [x] Node runs in OSX and devenv
- [x] All tests in `./test.sh` pass

### CODE REVIEW

**Comment by iameli** [comment]
I'ma merge this into the new `media-integration` branch, test it out in the Wowza workflow.

**Comment by j0sh** [comment]
Rebased to master, changed from a vendored LPMS update to using `go mod` via  `go get -u github.com/livepeer/lpms`. Let me know if it's done incorrectly.

I'd like to hold off on merging this until the fix for https://github.com/livepeer/lpms/issues/154 is in.

**Comment by darkdarkdragon** [comment]
@j0sh it's better to add version tag to `lams` repo, this will allow go.mod to use it as reference, so instead of 
`github.com/livepeer/lpms v0.0.0-20190913184151-0246c39344c6` it will be 
`github.com/livepeer/lpms v0.1.0` (if we will add `v0.1.0` as tag to current `lpms` master)

**Comment by j0sh** [comment]
@darkdarkdragon I guess this means we'd have to update the version every time we do a sync with go-livepeer which seems mildly annoying? (And that presumes that go-livepeer is the only user of LPMS, which is probably accurate for now, but it does make me question why we have a separate library at all.)

**Comment by darkdarkdragon** [comment]
@j0sh 
>  I guess this means we'd have to update the version every time we do a sync with go-livepeer

yes

> which seems mildly annoying

why? for me it's seems logical - it will clearly distinct versions we intend to be used in other projects (yes, in `go-livepeer` :)

> And that presumes that go-livepeer is the only user of LPMS

why?

> but it does make me question why we have a separate library at all

at least for the sake of decoupling our components :)

**Comment by mkrufky** [comment]
separation of components into logical parts is a good thing - version dependency changes are always tough to adjust to at first, but in the longrun, it will be better for the organization of the project.   Having LPMS as a separate module is immensely important, because we want to be able to enable developers to build upon our technology.

**Comment by j0sh** [comment]
>>And that presumes that go-livepeer is the only user of LPMS
>
> why?

Suppose we had a dozen projects using LPMS, then the workflow of bumping upstream LPMS version each time a downstream dependency needs a particular change doesn't make sense. (If we ever hit the point of having dozens of downstream dependencies, we may want to commit to formal releases with an actual compatibility and versioning policy, but that step seems premature right now.)

Basically I'm a little skeptical of introducing a mandatory workflow change if we're not going to do actual, formal releases of LPMS. Is there any reason other than aesthetics to do this? (Which would be a somewhat strange reason for a file that's essentially machine generated and machine readable.)

Hashes seem to give us everything we need and are immediately comprehensible (at least to me). I'm not sure where/how the version number works - within a `go mod` config? A special file? Is it a `git tag` convention? What if more commits are added on top after defining a particular version - how does `go mod` resolve that? (Yeah, I could google all this and figure it out, but the basic point is the semantics of a "version number" here aren't immediately obvious, while the hash unambiguously points to a very specific snapshot of the code, and that seems preferable... at least, preferable to me.)

**Comment by j0sh** [comment]
Rebased to update LPMS to https://github.com/livepeer/lpms/commit/7f095b315d48969f313aaa1152ac1b9ab6ad1509

Not sure why there are those extra lines in `go.sum` though, they seem somewhat redundant.

https://github.com/livepeer/go-livepeer/pull/1073/files#diff-f949e2d81c8076ebbf8af38fcbb72c1f

**Comment by mkrufky** [comment]
> Rebased to update LPMS to [livepeer/lpms@7f095b3](https://github.com/livepeer/lpms/commit/7f095b315d48969f313aaa1152ac1b9ab6ad1509)
> 
> Not sure why there are those extra lines in `go.sum` though, they seem somewhat redundant.
> 
> https://github.com/livepeer/go-livepeer/pull/1073/files#diff-f949e2d81c8076ebbf8af38fcbb72c1f

@j0sh please do `go mod tidy` and then check in the results.

**Comment by j0sh** [comment]
After `go mod tidy` :

```diff
commit 7df3e331e47c4e822a4997982551ea194fc94349
Author: Josh Allmann <joshua.allmann@gmail.com>
Date:   Wed Sep 18 14:41:49 2019 -0700

    mod: go mod tidy

 go.mod |  22 ++++---
 go.sum | 545 ++++++++++------------------------------------------------------------------------------------------------------------------------------------------------------
 2 files changed, 49 insertions(+), 518 deletions(-)
```

**Comment by mkrufky** [comment]
> After `go mod tidy` :
> 
> ```diff
> commit 7df3e331e47c4e822a4997982551ea194fc94349
> Author: Josh Allmann <joshua.allmann@gmail.com>
> Date:   Wed Sep 18 14:41:49 2019 -0700
> 
>     mod: go mod tidy
> 
>  go.mod |  22 ++++---
>  go.sum | 545 ++++++++++------------------------------------------------------------------------------------------------------------------------------------------------------
>  2 files changed, 49 insertions(+), 518 deletions(-)
> ```

Looks like some other dependencies got updated as well, but the duplicated lpms entries are removed :-)

You can also experiment with `go mod update` to update them all or `go get` to fetch specific revisions of any dependency

**Comment by darkdarkdragon** [comment]
@j0sh 
> I'm not sure where/how the version number works - within a go mod config

if your right now tag current lpms HEAD wit tag `v.0.1.0` - then in `go.mod` it will be
`github.com/livepeer/lpms v0.1.0`
if you then add new commit on top of It - it will look like
`github.com/livepeer/lpms v0.1.0-20190820150402-f1b88b60503b`

>  here aren't immediately obvious, 

it's pretty obvious - it's a git's tag == just named commit
for me it looks better because it shows intent to release tagged changes, not just pointing to random commit in the tree.
but yeah, with only one user it's not that important

>  Is there any reason other than aesthetics to do this?

no, aesthetics only

**Review by mk-livepeer — APPROVED** [review]

**Review by darkdarkdragon — APPROVED** [review]

**Comment by j0sh** [comment]
> Looks like some other dependencies got updated as well

Hmm that could be risky, but this is a good time as any to update those dependencies. We'll need to be a little more careful about this as the release draws closer though.

**Pull request merged**
