### PR TITLE
Init winning ticket value redeemed stat on boot

### PR DESCRIPTION
**Pull request by stronk-dev**
**What does this pull request do? Explain your changes. (required)**

So before #2888 got merged, the winning ticket metric wasn't working properly. At least, when graphing the metric using `livepeer_winning_tickets_recv` you could see that it was counting them tickets, but when querying the increase over time (ie using `sum by (datacenter)(increase(livepeer_winning_tickets_recv[7d]))`) it would be short one or more tickets.

On every restart of the node the prometheus counters and gauges get reset. So using `increase` is the way to correctly display an increasing counter of tickets across restarts of the node

I am currently seeing the same behaviour with `livepeer_value_redeemed`
image
where on the first winning ticket, it counts it as an increase of 0, but then the next ticket gets counted correctly

Here is my theory: when the node boots, not all parameters have their values initialised to 0. It seemd that `increase` does not count an increase from null -> 1, but it does count an increase from 0 -> 1

This PR initialised the `value_redeemed` stat to 0 on boot, which should fix the issue i am seeing

**How did you test each of these updates (required)**
Not yet tested, deploying now...

### CODE REVIEW

**Comment by rickstaa** [comment]
This will fix #2917.

**Comment by FranckUltima** [comment]
Thank you! So happy to see this point finally resolved! I don’t know how long I spent on Grafana trying to find the query that would give me the exact number of winning tickets, even after a server restart, without ever succeeding.

**Comment by stronk-dev** [comment]
> Thank you! So happy to see this point finally resolved! I don’t know how long I spent on Grafana trying to find the query that would give me the exact number of winning tickets, even after a server restart, without ever succeeding.

Lol I know how you feel, when @papabear99 PR was merged it fixed the `livepeer_winning_tickets_recv` as an unintended side effect, so just applying the same logic to `livepeer_value_redeemed` now. we can finally accurately track work performed vs payouts redeemed

**Review by thomshutt — APPROVED** [review]
Looks good, thanks @stronk-dev!

**Pull request merged**
