### PR TITLE
release v0.5.38

### PR DESCRIPTION
**Pull request by thomshutt**
### Breaking Changes 🚨🚨

None

#### Broadcaster
- [#2709](https://github.com/livepeer/go-livepeer/pull/2709) Add logging for high keyframe interval, reduce log level for discovery loop
- [#2684](https://github.com/livepeer/go-livepeer/pull/2684) Fix transcode success rate metric
- [#2740](https://github.com/livepeer/go-livepeer/pull/2740) Fix incorrect processing of VerificationFreq parameter
- [#2735](https://github.com/livepeer/go-livepeer/pull/2735) Fix EndTranscodingSession() call and potential race
- [#2747](https://github.com/livepeer/go-livepeer/pull/2747) Fixed a transcoding bug that occurred when remote transcoder was removed

#### General
- [#2713](https://github.com/livepeer/go-livepeer/pull/2713) Add support for keyfiles with -ethKeystorePath, update flag descriptions, flagset output to stdout

### CODE REVIEW

**Review by leszko — APPROVED** [review]

**Comment by leszko** [comment]
@thomshutt How about waiting for these 2 PRs and including them in the release?
- https://github.com/livepeer/go-livepeer/pull/2713
- https://github.com/livepeer/go-livepeer/pull/2747

**Comment by thomshutt** [comment]
@leszko I did consider that, but wasn't sure how long it'd be until they're merged

**Comment by eliteprox** [comment]
> @leszko I did consider that, but wasn't sure how long it'd be until they're merged

Both #2713 and #2747 ready for review again

**Comment by thomshutt** [comment]
@leszko those two PRs are now in

**Pull request merged**
