### PR TITLE
Recover transcoder state after restart.

### PR DESCRIPTION
**Pull request by j0sh**
* [x] Track DB version and provide a migration path
* [x] Track last seen block (for later use in replaying the event log)
* [x] Track jobs to reconnect to active jobs
* [x] Track receipts for claims
* [x] Submit incomplete claims

### CODE REVIEW

**Comment by j0sh** [comment]
Since we are doing the DB calls within ClaimManager now (https://github.com/livepeer/go-livepeer/pull/358/commits/8eb57f91ce41136220edc41b58816a8418c36bf6) , we had to move all the DB code out of `core/` and into `common/` in order to avoid circular imports. All dependent commits have been fixed up, so the tree compiles and tests cleanly at each commit in this PR.

**Comment by j0sh** [comment]
Updated to use the new libp2p, however circle is failing (as usual). The same test command works locally.

**Comment by j0sh** [comment]
The bulk of the implementation should be complete; any changes will be fixes and additional testing.

Some notes about the implementation of claims/receipt recovery[1][2][3]. Since we don't really keep track of job or claim manager instances anywhere (https://github.com/livepeer/go-livepeer/issues/376), the simplest way to recover was to create a new claims manager for recovered receipts, and submit from there. If the same job is also recovered, there may be *two* claim managers for the job, but only one is actually attached to the job service. The "recovery" claim manager should be able to run independently for the old segments, with new incoming segments going to the job service's claim manager. After recovery is complete, golang *should* clean up the recovery claim manager so it doesn't linger in memory.

Does anyone foresee any issues with the above? @ericxtang @yondonfu 

One behavioral change to the existing implementation: we no longer remove the broadcast segment from disk, and wait until after fee distribution completes to do so [4]. Needed in order to present segments for verification.

[1] Insert receipts in db https://github.com/livepeer/go-livepeer/pull/358/commits/9c4331504a893e548aa1ebd3bd269f7ba3898cc2
[2] Insert claims in db https://github.com/livepeer/go-livepeer/pull/358/commits/6c5e1a51e10acb8855bbc84c528122a6eeccb049
[3] Claims/receipt recovery https://github.com/livepeer/go-livepeer/pull/358/commits/e44078f0f1a0a6daee7c5c5c4b07b73da8aaba5e
[4]  Removing segment from disk only after distribution https://github.com/livepeer/go-livepeer/pull/358/commits/04c93fddda4c1dc6df83ee61640fd91549375492

**Comment by j0sh** [comment]
> Does anyone foresee any issues with the above?

After further testing, this method isn't entirely reliable right now: if receipts is recovered and submitted, any recovered jobs need to be aware of the latest claim number. We could query the blockchain for the job after the tx is confirmed and use `TotalClaims - 1` as the latest ID, but it's fairly racy. The best solution would be to fix https://github.com/livepeer/go-livepeer/issues/376 or return a claim object (plus ID) from the transaction itself.

**Comment by j0sh** [comment]
Here's some more color on https://github.com/livepeer/go-livepeer/pull/358#issuecomment-385144955.

### Problem Description

With separate claim managers for recovery and the job itself, we run into a possible reentrancy issue.
```
Claim tx1 submitted (for recovered receipts). Assume claimID=1
Claim tx2 submitted (for a recovered job). Assume claimID=2
tx2 is committed to a block. tx2 claim is now claimID=1
tx1 is committed to a block. tx1 claim is now claimID=2
...
Attempt to verify claim in tx1 using claimID=1
Verification fails because claimID=1 == tx2, transcoder slashed 
```
The issue here arises because once the claim tx is confirmed, we don't actually have the claim that was written on-chain; we need to use the claimID to fetch the claim[1].  However, the claimID is generated by the protocol, not the node. So any claimID the node has when it submits the transaction is presumptive.  🥚 🐣 🐤  

### Working Solution

Now, this issue probably won't happen often (or at all); it's merely a possibility. Instead of trying to fix the problem immediately, let's monitor the issue. We do this by checking the on-chain claim corresponding to the presumed `claimID` . If the on-chain claim doesn't match what we have locally, log an error (in the DB) and fail out [2]. From there, we can gauge the actual impact of this issue (through user reports) before attempting to make this process watertight, which would entail (perhaps unwarranted) additional complexity.

### Alternatives

* Ensure we only have one claim manager per job, running at a time. This would also solve https://github.com/livepeer/go-livepeer/issues/376 . However, this also introduces additional concurrency concerns; any cross-goroutine calls to `ClaimVerifyAndDistrubuteFees` would need to be serialized [3].

* Search the claimID "neighborhood" to find one that matches, +/- a couple IDs.

* Use the tx id to determine what was written on-chain, rather than using the claimID.

*  Transcoder can subscribe to the NewClaim contract event which is emitted every time a transcode claim is submitted on-chain - the event will include the transcoder's address, the job ID and the claim ID.

### Future Actions

We'll monitor for this issue and develop a better solution if it's necessary. After this settles down, I might submit a LIP to remove the claimID from the contract and use the segment range for indexing, which would resolve a host of concerns.

[1] https://github.com/livepeer/go-livepeer/blob/master/eth/claimmanager.go#L293-L295
[2] https://github.com/livepeer/go-livepeer/pull/358/commits/15619346f345f88b74f432dab585165511925750#diff-a776aba743c0cf86c5c34fc5236506eeR324
[3] Recovery and the job can't run on the same goroutine since they are both time-sensitive; recovered receipts need to be claimed before the 256 block threshold, while we don't want to delay job reconnects until the first claim completes.

**Comment by yondonfu** [comment]
An addition to the alternative of using the tx ID - the transcoder can subscribe to the NewClaim contract event which is emitted every time a transcode claim is submitted on-chain - the event will include the transcoder's address, the job ID and the claim ID. Since the transcoder address is indexed in the event, the transcoder can subscribe to only the NewClaim events that include itself. After submitting a claim, the transcoder waits for the transcode claim to confirm on-chain and to receive the claim ID in the emitted event. If concurrency is a worry due to the node's use of multiple claim managers, for a given claim ID received in a NewClaim event the transcoder can check that tx ID associated with the received NewClaim event matches the ID of the tx it originally submitted

**Comment by ericxtang** [comment]
I personally like the event subscription solution.  It feels cleaner.  Transcoders can bypass the Infura websocket issue by running a local Geth/Parity and using an IPC connection.

**Comment by j0sh** [comment]
Agreed that is a better solution than most of the ones we have so far. Added that option to the alternatives.

Since we can't guarantee transcoders will be running their own Ethereum nodes, we would probably still want to make that robust against duplicate events -- we should strive to avoid the possibility of slashing due to implementation quirks. Not much we can do about missed events though, I think.

Should this be implemented before the merge, or shall we monitor the issue first?

**Comment by yondonfu** [comment]
I think it would make sense to push forward with this PR and implement a solution to the described race condition in a separate follow up PR as this PR already looks pretty big. I imagine if we do end up going with the event subscription solution, we'll have some kinks to work out with the unstable event subscription process when using Infura's WebSockets API.

**Pull request merged**
