### PR TITLE
adding 25fps

### PR DESCRIPTION
**Pull request by ericxtang**
**What does this pull request do? Explain your changes. (required)**

Adding 25fps transcoding profile.  In combination with https://github.com/livepeer/lpms/pull/159

**Specific updates (required)**

- Adding 25fps video profile

**How did you test each of these updates (required)**

Manual testing

**Does this pull request close any open issues?**

**Checklist:**

- [x] README and other documentation updated
- [x] Node runs in OSX and devenv
- [x] All tests in `./test.sh` pass

### CODE REVIEW

**Comment by iameli** [comment]
Note that any new profiles also need to be added here to be used in the API: https://github.com/livepeer/livepeerjs/blob/master/packages/sdk/src/index.js#L23

**Comment by j0sh** [comment]
To clarify the reason for adding these profiles: is it because we because we observed input coming in at 25fps, and this made the mediastreamvalidator complain about mismatched framerates in the master playlist vis-a-vis our 30fps output options?

This would imply that we need to compute the input frame rate prior to selecting a matching bitrate ladder for transcoding. This may not always be feasible for a number of reasons: 

* The input may be configured as VFR, or adjust mid-stream
* "Constant" fps input may end up being erratic due to drops, eg at the capture side
* The input itself may be an "odd" frame rate
* The actual framerate may not always be signaled and would sometimes need to be approximated.

There are a few other ways we can work around the issue and make mediastreamvalidator happy:

* Omit the source stream from the master playlist. Only make the transcoded renditions available. This would be 30/60fps all around.
* Use a FPS in a "pass-through" configuration that preserves the framerate of the input stream. See https://github.com/livepeer/lpms/issues/120

With all that being said, this type of patch feels quite ad-hoc, because it only addresses the one specific case we've observed, rather than generalizing the solution. That also points to some deeper issues with how we configure out output renditions: it may be time to move away from a hardcoded set of presets and enable full transcoder configurability throughout the network.

**Comment by iameli** [comment]
> To clarify the reason for adding these profiles: is it because we because we observed input coming in at 25fps, and this made the mediastreamvalidator complain about mismatched framerates in the master playlist vis-a-vis our 30fps output options?

It's not about mediastreamvalidator - we have a specific customer ask for 25fps. The downstream client is the Wowza plugin, so we can lean on Wowza to provide us the source framerate information prior to picking a preset in the API.

I agree with everything you're saying about what we should do moving forward though.

> That also points to some deeper issues with how we configure out output renditions: it may be time to move away from a hardcoded set of presets and enable full transcoder configurability throughout the network.

That's https://github.com/livepeer/go-livepeer/issues/811, yeah?

**Comment by ericxtang** [comment]
@j0sh and @iameli - I'm supportive for solving this problem by allowing users to dynamically specify the transcoder configuration.

**Comment by j0sh** [comment]
> That's #811, yeah?

That's part of it - #811 primarily covers the webhook and is one possible interface for supplying the transcoding configuration. The RPC handling between B/O/T would need to be updated as well, including protobuf messages. Hopefully that's it, but there might be a couple other things I'm forgetting.

**Comment by ericxtang** [comment]
@j0sh can you approve?

**Review by j0sh — APPROVED** [review]

**Pull request merged**
