### PR TITLE
Update help descriptions for {min,max}GasPrice

### PR DESCRIPTION
**Pull request by Strykar**
This is no longer in Wei, Arbitrum calls it ArbGas - https://developer.offchainlabs.com/docs/arbgas
PRs for the docs and livepeer_cli (to be linked)

**What does this pull request do? Explain your changes. (required)**
Updates https://github.com/livepeer/go-livepeer/pull/2041

**Checklist:**

- [x] Read the [contribution guide](./doc/contributing.md)
- [ ] `make` runs successfully
- [ ] All tests in `./test.sh` pass
- [x] README and other documentation updated
- [ ] [Pending changelog](./CHANGELOG_PENDING.md) updated

### CODE REVIEW

**Comment by leszko** [comment]
@Strykar I think the Arbitrum still uses wei and gwei. Look here: https://developer.offchainlabs.com/docs/arbos_formats

> ArbGas price bid, in wei (uint)

**Comment by Strykar** [comment]
> > ArbGas price bid, in wei (uint)

Is 1 ArbGas wei == 1 ETH wei?
Orchestrators track Gas on Arbitrum now not L1, so what does this option do on L2?

**Comment by leszko** [comment]
Good question. Please check the [related discussion in Discord](https://discord.com/channels/423160867534929930/426114749370204170/960804699609640960).

**Comment by yondonfu** [comment]
See related comment here https://github.com/livepeer/docs/pull/206#issuecomment-1091708920

**Pull request closed without merging**
