### PR TITLE
Dockerfile for building livepeer node on Windows.

### PR DESCRIPTION
**Pull request by darkdarkdragon**
**What does this pull request do? Explain your changes. (required)**
New Dockerfile for building on Windows. Based on previous Eli work.
Here I've split out ffmpeg building part into separate Dockerfile (it is in docker-livepeer repo).
Also there is Powershell script (windows build.ps1) which automates building Livepeer executable and getting it out of Docker container.

**Specific updates (required)**
Added Dockerfile and Powershell script.

**How did you test each of these updates (required)**
Manually.

**Does this pull request close any open issues?**

**Checklist:**

- [x] README and other documentation updated
- [ ] Node runs in OSX and devenv
- [ ] All tests in `./test.sh` pass

### CODE REVIEW

**Comment by iameli** [comment]
Nice catch with the `docker cp` fix! I'll give this a shot in a few environments tomorrow.

**Comment by iameli** [comment]
Hmm, I'm not able to build the builder image on Windows 10...

```
PS C:\Users\iameli\code\docker-livepeer\ffmpeg> docker build -m 4gb -t livepeer/ffmpeg-base:windows -f Dockerfile.ffmpeg
-windows .
Sending build context to Docker daemon  9.216kB
Step 1/18 : FROM mcr.microsoft.com/windows/servercore:ltsc2019 as builder
ltsc2019: Pulling from windows/servercore
no matching manifest for unknown in the manifest list entries
```

**Comment by darkdarkdragon** [comment]
I see this message only when docker running in 'Linux containers' mode. In 'Windows containers' mode it pulls mentioned image without problems.

**Comment by iameli** [comment]
Incorporated into #887, thanks!

**Pull request closed without merging**
