### PR TITLE
cmd/livepeer: Add support for `-j` flag for mist connector

### LINKED ISSUE #2181: Add `-j` flag to the built binary
This is to facilitate with the final binary being run with mistcontroller runtime.

### PR DESCRIPTION
**Pull request by hjpotter92**
**What does this pull request do? Explain your changes. (required)**
Add support for `-j` flag to the built binaries which prints json information. This json is used by mist controller to launch dependent applications.

**Specific updates (required)**

- [x] Add `-j` flag to `livepeer` binary

**How did you test each of these updates (required)**
Building the package locally, and testing with an added controller in mist runtime configuration.

**Does this pull request close any open issues?**
related to #2181 

**Checklist:**

- [x] Read the [contribution guide](./doc/contributing.md)
- [x] `make` runs successfully
- [x] All tests in `./test.sh` pass
- [x] README and other documentation updated
- [x] [Pending changelog](./CHANGELOG_PENDING.md) updated

### CODE REVIEW

**Review by victorges — APPROVED** [review]
LGTM! 

You might also want to update the CHANGELOG-PENDING file so we include it on the next release changelog. Could mention that this new flag is for support for Mist plugins environment, or something like that

**Comment by victorges** [comment]
FTR I updated the PR description to match the go-livepeer pattern as well. We should always prefix with the package that is being updated

**Review by yondonfu — COMMENTED** [review]
+1 for the comments by @victorges on changelog [1] + commit structure. Other than that looks good!

[1] See https://github.com/livepeer/go-livepeer/blob/master/doc/contributing.md#changelog

**Comment by hjpotter92** [comment]
> LGTM!
> 
> You might also want to update the CHANGELOG-PENDING file so we include it on the next release changelog. Could mention that this new flag is for support for Mist plugins environment, or something like that

Updated the pending changelog! Thanks for the pointers :)

---

I'm also not sure why the build tests are failing after changelog updates :sweat_smile:

**Pull request merged**
