### PR TITLE
Add E2E test to GH Action

### LINKED ISSUE #2318: Operationalize E2E Tests (test script, GH action)
We need to integrate E2E tests in our CI, so that they run with every PR and push to master.

For this purpose:
- create `test_e2e.sh` script similar to [test.sh](https://github.com/livepeer/go-livepeer/blob/master/test.sh) which executes only E2E tests
- exclude E2E tests from `test.sh`
- Add `test_e2e.sh` to [test GH action](https://github.com/livepeer/go-livepeer/blob/master/.github/workflows/test.yaml) or create a separate `test_e2e` GH Action

Note that we need `test_e2e.sh` as a separate script, not run in `test.sh`, because the requirement for running `test_e2e.sh` is to have a running Docker daemon available.

### PR DESCRIPTION
**Pull request by leszko**
fix #2318

### CODE REVIEW

**Comment by hjpotter92** [comment]
wouldn't the `./...` testing defined in `test.sh` cover this?

```sh
go test -coverprofile cover.out ./...
```

**Comment by leszko** [comment]
> wouldn't the `./...` testing defined in `test.sh` cover this?
> 
> ```shell
> go test -coverprofile cover.out ./...
> ```

E2E tests are excluded from `test.sh` with 
```
$(go list ./... | grep -v 'test/e2e')
```

I did it on purpose. E2E test have a different requirements (you need to have (amd64) Docker daemon running).

**Review by thomshutt — APPROVED** [review]

**Comment by thomshutt** [comment]
Is it possible to run them in parallel with the regular tests?

**Comment by leszko** [comment]
> Is it possible to run them in parallel with the regular tests?

Do you mean a separate GH Action workflow? Yes, we could do it. But for now I think it's not needed. E2E tests are super short comparing to the usual tests. So, let's wait, when they grow in terms of execution time, we can move them to a separate workflow. Maybe we could be even more granular with tests.

**Comment by hjpotter92** [comment]
> I did it on purpose. E2E test have a different requirements (you need to have (amd64) Docker daemon running).

but the current change doesn't actually setup the docker daemon (not sure if github runners have that by default); and only removes the e2e tests from coverage reports.

To add docker daemon as a dependency here, you might need to declare a service:

```yaml
service:
  docker:
    image: docker:latest
```
the image might be `docker:dind` depending on how the e2e tests function.

**Comment by leszko** [comment]
GH Runners have Docker by default. So no need to add anything. You can check, I actually merged this PR and everything works fine.

**Pull request merged**
