### PR TITLE
Bump nvidia cuda docker image version

### PR DESCRIPTION
**Pull request by stronk-dev**
Old version was removed, docker builds require a version bump. Not sure if this breaks anything

### CODE REVIEW

**Comment by leszko** [comment]
I see that it increased the Docker image size from `1.29GB` to `2.38GB`. Isn't that an issue? CC: @thomshutt @hjpotter92

**Comment by hjpotter92** [comment]
> I see that it increased the Docker image size from `1.29GB` to `2.38GB`. Isn't that an issue? CC: @thomshutt @hjpotter92

image sizes aren't a problem now. we are provisioning our machines to use the entire SSD storage; instead of earlier 50GB as `/` partition and rest as `/data`. each server now has atleast 500GB of disk space to store docker images in cache and the persitant storage is handled separately (if needed).

**Comment by thomshutt** [comment]
@hjpotter92 that's true, but it still makes it more unwieldy to work with, slower to build etc. and so if there is a way to keep it down then that's probably worth exploring

**Comment by leszko** [comment]
I see the version `12.x` is small, so we may upgrade to it. Just need to think how to test it.

**Comment by hjpotter92** [comment]
I believe the last time this was discussed, @iameli raised an issue with `ubuntu18.04` also getting bumped. if we're planning to keep ubuntu18.04 as the supported runtime version, we should go with 11.6.2 as that has [the smallest image size](https://hub.docker.com/r/nvidia/cuda/tags?page=1&ordering=last_updated&name=8-runtime-ubuntu18.04).

however, if we're also planning to ditch the now EOL-ed ubuntu18.04, should we also consider ubuntu20? I believe when we reprovisioned our infra, the machines were installed with ubuntu20 (and that had been the concern last time this image was bumped).

**Review by leszko — APPROVED** [review]

**Pull request merged**
