### PR TITLE
ci: Update to ubuntu 20.04 for building docker image

### PR DESCRIPTION
**Pull request by jailuthra**
**What does this pull request do? Explain your changes. (required)**

[Latest docker build](https://github.com/livepeer/go-livepeer/actions/runs/1234910009) for `master` is failing because Ubuntu 16.04 is no longer supported as a build environment for Github Actions.
Updating to 20.04 here.

**Specific updates (required)**

*See commits*

**How did you test each of these updates (required)**

- [x] CI builds pass

**Does this pull request close any open issues?**

**Checklist:**

- [ ] Read the [contribution guide](./doc/contributing.md)
- [ ] `make` runs successfully
- [ ] All tests in `./test.sh` pass
- [ ] README and other documentation updated
- [ ] [Pending changelog](./CHANGELOG_PENDING.md) updated

### CODE REVIEW

**Review by yondonfu — COMMENTED** [review]
The [Linux](https://github.com/livepeer/go-livepeer/blob/master/.github/workflows/linux.yml#L9) and [Linux Tensorflow](https://github.com/livepeer/go-livepeer/blob/master/.github/workflows/linux-tensorflow.yml#L9) builds use ubuntu 18.04. Let's use this opportunity to move all of them onto ubuntu 20.04?

**Comment by jailuthra** [comment]
> The Linux and Linux Tensorflow builds use ubuntu 18.04. Let's use this opportunity to move all of them onto ubuntu 20.04?

Somehow `gnutls-3.7.0` build process isn't happy with Ubuntu 20.04 and I'm out of ideas.
Leaving the non-docker builds on 18.04 right now.

**Comment by yondonfu** [comment]
> Somehow gnutls-3.7.0 build process isn't happy with Ubuntu 20.04 and I'm out of ideas.

Weird. Let's come back to this later then.

**Review by yondonfu — APPROVED** [review]
LGTM

**Pull request merged**
