### PR TITLE
implement a custom error type for max transcode attempts

### PR DESCRIPTION
**Pull request by mjh1**
**What does this pull request do? Explain your changes. (required)**

Created a custom error and used multi-error wrapping to avoid needing to do any string matching in the error handling.

**Specific updates (required)**

**How did you test each of these updates (required)**

I modified the existing unit test.

**Does this pull request close any open issues?**

**Checklist:**

- [x] Read the [contribution guide](./doc/contributing.md)
- [x] `make` runs successfully
- [x] All tests in `./test.sh` pass
- [x] README and other documentation updated
- [x] [Pending changelog](./CHANGELOG_PENDING.md) updated

### CODE REVIEW

**Comment by cyberj0g** [comment]
@mjh1 thanks for looking into that.
I had a slightly more generic solution in mind, like, a wrapper to add more detailed error message along with custom error type, without masking the root error:
```
ErrFancyCustomError  = errors.New("custom message")
...
func faulty() error {
    err = ...
    return fmt.Errorf("even more detailed message: %w", lperrors.Error(ErrFancyCustomError, err))
    // with a pre-defined message and error type, but root cause error is also included
    // return lperrors.Error(ErrFancyCustomError, err)
}
...
anErr = faulty()
if errors.Is(anErr, ErrFancyCustomError) {
// true
}
// anErr printed like this:
// custom message: even more detailed message: context cancelled
```
Also, I think it's not a good idea to use `errors` as a package name, because there's a builtin package with the same name. Maybe I'm inventing the wheel here, let me know what you think.

PS: it's not a high priority feature

**Comment by mjh1** [comment]
@cyberj0g yeah I was trying to figure out a way to make it generic, it's a little fiddly but I think my latest change should be good enough. It'll get a lot easier in go 1.20 we'll be able wrap multiple errors: https://tip.golang.org/doc/go1.20#errors

**Comment by cyberj0g** [comment]
> https://tip.golang.org/doc/go1.20#errors

Cool! Maybe we could just backport some functions we are interested in, such as: `errrors.Is`, `fmt.Errorf` from 1.20 to a `lperrors` package, and then delete that, once we move go-livepeer to Go 1.20? These functions are few lines usually, it shouldn't be too hard.

**Comment by mjh1** [comment]
ah good plan 👍

**Comment by mjh1** [comment]
@cyberj0g annoyingly i'm not sure it's possible, the `Is` function makes use of this internal reflection package: https://github.com/golang/go/blob/go1.20rc3/src/errors/wrap.go#L8 
what do you think?

**Comment by cyberj0g** [comment]
Ok, let's draft that until Go 1.20 is released. Thanks for researching!

**Review by thomshutt — APPROVED** [review]
Beautiful

**Pull request merged**
