### PR TITLE
eth/accountmanager: allow generation with a provided password

### PR DESCRIPTION
**Pull request by iameli**
Facilitates a wallet to be created and repeatedly accessed using external tools, e.g. catalyst. Open to other designs if folks think this is a a bad idea.

### CODE REVIEW

**Review by leszko — COMMENTED** [review]
The `passphrase` change looks good to me, however I just wonder about this adding test coverage part. It seems that the commit https://github.com/livepeer/go-livepeer/pull/2368/commits/2ce6496ff9516792e2f2209600cb2dbd4eb96038 does not correspond to this PR.

Also, from what I see in the logs, uploading this code coverage actually failed.

**Comment by hjpotter92** [comment]
> I just wonder about this adding test coverage part.

hmm, I just hijacked Eli's PR to add the test coverage reporting. I was considering b/w [coveralls](https://coveralls.io/) and codecov for reporting, went with codecov as they have better dashboard UX :)

> Also, from what I see in the logs, uploading this code coverage actually failed.

The upload worked. just that there's no coverage reports from the default/master branch available, the codecov app is unable to show coverage difference on dashboard (plus I think it needs some configuration from github org admin). check screenshot below (there's a notice about installing github app)

image

**Comment by leszko** [comment]
> > I just wonder about this adding test coverage part.
> 
> hmm, I just hijacked Eli's PR to add the test coverage reporting. I was considering b/w [coveralls](https://coveralls.io/) and codecov for reporting, went with codecov as they have better dashboard UX :)

hehe, ok, could you please move it to a separate PR? I think it does not fit here :) Then, we can discuss the coverage separately.

**Comment by hjpotter92** [comment]
> > > I just wonder about this adding test coverage part.
> > 
> > 
> > hmm, I just hijacked Eli's PR to add the test coverage reporting. I was considering b/w [coveralls](https://coveralls.io/) and codecov for reporting, went with codecov as they have better dashboard UX :)
> 
> hehe, ok, could you please move it to a separate PR? I think it does not fit here :) Then, we can discuss the coverage separately.

Done; ref. #2372 :)

**Comment by leszko** [comment]
> Done; ref. #2372 :)

Thank you 🙏

**Review by leszko — APPROVED** [review]
👍

**Review by thomshutt — APPROVED** [review]

**Pull request merged**
