### PR TITLE
Embed IPFS node

### PR DESCRIPTION
**Pull request by yondonfu**
Previously we were using the `os/exec` package to invoke an IPFS daemon and assumed that the user already had IPFS installed locally. This involved using `go-ipfs-api` to interact with the daemon process which required setting up the proper API and gateway ports. I wasn't sure what was causing the crashes when we tried uploading files using that setup and it was difficult to debug because the daemon did not provide very descriptive exit errors. So, I ended up directly embedding `go-ipfs` in this PR which seems to fix the crashes during file upload. I also think it is a plus that the user does not have to also download an IPFS binary and potentially provides greater/more flexible programmatic control over IPFS operations . A downside might be the bigger binary - its ~37.8 MB right now.

Might be easier to review this by looking at the first commit. The second commit is just vendoring stuff.

### CODE REVIEW

**Comment by yondonfu** [comment]
Hm for some reason go-ipfs seems to have been committed as a submodule so the CI tests fail because they're not pulling down go-ipfs...looking into this

**Comment by yondonfu** [comment]
Turns out it was because I forgot to remote the `.git` directory in the vendored go-ipfs package 😅

**Review by dob — COMMENTED** [review]
Any idea if this will run into trouble if there's already an existing IPFS process running on the machine? Port conflicts or anything?

**Comment by yondonfu** [comment]
If there is already a daemon running using the local repo path specified (i.e. like ~/.ipfs), go-livepeer would throw a resource temporarily unavailable error. But, if there needed to be two IPFS processes running I think you could just use different repo paths - one for the local daemon, one for go-livepeer

**Review by dob — APPROVED** [review]
:ship: Embedded IPFS! Let's press on.

**Pull request merged**
