### PR TITLE
`m3u8` dependency move to Livepeer's repo

### PR DESCRIPTION
**Pull request by darkdarkdragon**
**What does this pull request do? Explain your changes. (required)**
All links changed from
`github.com/ericxtang/m3u8` to
`github.com/livepeer/m3u8`

**Specific updates (required)**
Only links changes

**How did you test each of these updates (required)**

**Does this pull request close any open issues?**

**Checklist:**

- [ ] README and other documentation updated
- [ ] Node runs in OSX and devenv
- [ ] All tests in `./test.sh` pass

### CODE REVIEW

**Review by yondonfu — CHANGES_REQUESTED** [review]
Could we update the LPMS repo with the updated m3u8 package location and then reference that commit with a standalone commit here? Would be nice to follow this convention at least while we're still using vendored packages.

**Comment by darkdarkdragon** [comment]
My mistake, will fix it

**Comment by darkdarkdragon** [comment]
@yondonfu fixed

**Comment by yondonfu** [comment]
One small comment: could we update the commit referencing the LPMS change to use the following format:

livepeer/lpms@080d405

This format has the added benefit of GH UI auto-linking to the relevant repository.

**Comment by darkdarkdragon** [comment]
@yondonfu got it, fixed

**Review by yondonfu — APPROVED** [review]
LGTM 🚢

**Pull request merged**
