### PR TITLE
core, server: Update rapid to latest API.

### PR DESCRIPTION
**Pull request by j0sh**
**What does this pull request do? Explain your changes. (required)**

A number of things have broken in the rapid library since the last version:

* go mod address is now pgregory.net/rapid
* Plurals are removed from some function names
* State machine executor function has been renamed

**Specific updates (required)**

- Updates rapid to latest release, v0.4.0 
- Updates API as necessary
- 

**How did you test each of these updates (required)**

Unit tests pass.

**Does this pull request close any open issues?**

**Checklist:**

- [ ] README and other documentation updated
- [ ] Node runs in OSX and devenv
- [x] All tests in `./test.sh` pass

### CODE REVIEW

**Review by yondonfu — APPROVED** [review]
LGTM 🚢

**Review by yondonfu — CHANGES_REQUESTED** [review]
Actually looks like another import needs to be fixed. From [CI](https://app.circleci.com/pipelines/github/livepeer/go-livepeer/1093/workflows/624be65b-48d0-4821-a9b8-636774e38593/jobs/6324):

```
Failed
package github.com/livepeer/go-livepeer/core (test)
	imports github.com/flyingmutant/rapid: import lookup disabled by -mod=readonly
```

**Comment by j0sh** [comment]
> Actually looks like another import needs to be fixed. From CI:

Yep - fixed it up.

**Comment by j0sh** [comment]
Third time's a charm. CI is green. ✅

**Review by yondonfu — APPROVED** [review]
LGTM!

**Pull request merged**
