### PR TITLE
Version 0.5.0

### PR DESCRIPTION
**Pull request by yondonfu**
**What does this pull request do? Explain your changes. (required)**

This PR bumps the node version to 0.5.0

**Specific updates (required)**

- Update `VERSION`

**Checklist:**

- [ ] README and other documentation updated
- [x] Node runs in OSX and devenv
- [x] All tests in `./test.sh` pass

### CODE REVIEW

**Comment by iameli** [comment]
Cool. This PR should produce the binaries - assuming they look okay we can merge.

**Comment by yondonfu** [comment]
Fixed missing node version in e6f19fc

**Comment by iameli** [comment]
Thanks! My bad, but it wouldn't be a major release unless we get tripped up at the last second 😄

**Review by iameli — APPROVED** [review]
Both binaries look good!

**Pull request merged**
