### PR TITLE
Move onto circle 2.0

### LINKED ISSUE #406: Move onto circle 2.0
We are currently on 1.0 and it's sunsetting in Aug.  https://circleci.com/blog/sunsetting-1-0/

The goal for this issue is to move Livepeer to circle 2.0.  This contains:
* Dockerizing the project
* Make sure the test script runs correctly in the docker container
* Make sure circleci errors get triggered correctly when tests fail
* Document how to run the docker container manually in the `Readme`

### PR DESCRIPTION
**Pull request by darkdarkdragon**
Fixes #406

### CODE REVIEW

**Comment by ericxtang** [comment]
Awesome work @darkdarkdragon!

**Comment by j0sh** [comment]
Awesome! Although this is already merged, a question: there seems to be quite a bit of overlap between the 'run' and 'cmd' specs in the .yml and Dockerfile. Is there a reason for that?

**Comment by f1l1b0x** [comment]
wow this was quick! gj!

**Comment by darkdarkdragon** [comment]
@j0sh circleci doesn't use Dockerfile
it generates it is own from config.yml, so them both are pretty same
small note - cicrcleci unconditionally caches all the stuff that `install_ffmpeg.sh` installs, and also this dependencies: 
```
      - run: go get github.com/golang/glog
      - run: go get github.com/ericxtang/m3u8
      - run: go get -u google.golang.org/grpc
      - run: go get github.com/jstemmer/go-junit-reportk
```
in case you will want to rebuilt them you will need to change `v3-pkg-cache` to something else, say `v4-pkg-cache`

**Comment by j0sh** [comment]
> circleci doesn't use Dockerfile

@darkdarkdragon So do we need the Dockerfile in here after all?

**Comment by j0sh** [comment]
I missed that the spec for this task had a Docker build as one of the requirements. I think we thought that circle 2 was using docker rather than a config.yml. Okay, awesome, then!

**Pull request merged**
