### PR TITLE
Revert "ci: protect Docker 'stable' tag (#3062)"

### PR DESCRIPTION
**Pull request by leszko**
Reverting your PR @rickstaa , because it stopped building docker images.

### CODE REVIEW

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
@leszko, my apologies for the confusion. The correct syntax is the one I used in the `ai-video` branch. It appears the last commit where I updated the syntax (as it was no longer functioning) was not included in the pull request to the main branch. You can view the commit here: [link](https://github.com/livepeer/go-livepeer/commit/2b8478d7c8cf9d64427732f55ad83b6c0e3c5794).

**Comment by hjpotter92** [comment]
> @leszko, my apologies for the confusion. The correct syntax is the one I used in the `ai-video` branch. It appears the last commit where I updated the syntax (as it was no longer functioning) was not included in the pull request to the main branch. You can view the commit here: [link](https://github.com/livepeer/go-livepeer/commit/2b8478d7c8cf9d64427732f55ad83b6c0e3c5794).

the default branch for this repo is not main 😅

**Comment by rickstaa** [comment]
@leszko, please feel free to merge this pull request or my new one: [PR #3068](https://github.com/livepeer/go-livepeer/pull/3068). This one is working, as you can see from the successful actions run: [link](https://github.com/livepeer/go-livepeer/actions/runs/9288247550/job/25559208908?pr=3068).

**Comment by rickstaa** [comment]
> > @leszko, my apologies for the confusion. The correct syntax is the one I used in the `ai-video` branch. It appears the last commit where I updated the syntax (as it was no longer functioning) was not included in the pull request to the main branch. You can view the commit here: [link](https://github.com/livepeer/go-livepeer/commit/2b8478d7c8cf9d64427732f55ad83b6c0e3c5794).
> 
> the default branch for this repo is not main 😅

Good catch will fix it now 👍🏻.

**Comment by leszko** [comment]
Cool, thanks @rickstaa . Merged your PR and closing this one.

**Pull request closed without merging**
