### PR TITLE
Make transactions compatible with Arbitrum and fix setting max gas price

### LINKED ISSUE #2084: Set -maxGasPrice flag equal to max fee per gas, current implementation makes spending unpredictable
I really would suggest to implement the `-maxGasPrice` as setting the max fee per gas. The current implementation makes it really unpredictable how much gas you'll end up spending. As an example: I just had a ticket redeemed at 155 gwei despite having set the maxGasPrice to 110: https://etherscan.io/tx/0x3b07dbf395c69fb028a63d69596c50d1b4c268aa5f4f417850089b9f69c5baea
Here's what happened: 
- In block 13536342, the base fee was at 109, which triggered the transaction. 
- This block and the next 2 were full, which caused the base fee to increase 12.5% per block. 
- Now since the tx was submitted with a priority fee of only 1 gwei, it is unlikely to be included during high demand/when blocks are full. I guess I was lucky since block 13536345 was almost empty, so my 1 gwei priority tx was included. 
- However, by then the base fee was at 155 gwei which means I ended up paying almost 50% more than expected.

With the current implementation, you could easily end up paying twice as much as your `-maxGasPrice` setting, which seems very counterintuitive to me.

### LINKED ISSUE #2243: Update transaction format for Arbitrum
**Is your feature request related to a problem? Please describe.**
Arbitrum treats the gas price differently than Ethereum. It uses `gasPrice` as the maximum gas price that a user may pay. Also Aribtrum probably does not accept the post-london upgrade transaction format.

**Describe the solution you'd like**
We need address the following points:
- Gas Price Monitor (oracle) does not make sense anymore
- Transaction Replacement does not make sense anymore
- All places where we use baseFee do not make sense anymore (there is no baseFee in Arbitrum)
- Setting max gas price is different

### PR DESCRIPTION
**Pull request by leszko**
**What does this pull request do? Explain your changes. (required)**

Fix setting max gas price for both legacy tx and dynamic fee tx. Additionally, fix the transaction replacement for the legacy tx.

This PR uses `TransactOpts` to set `GasFeeCap`. There was already another approach merged to solve this issue by modifying `TransactionManager` https://github.com/livepeer/go-livepeer/pull/2111, but it caused to stop processing streams https://github.com/livepeer/go-livepeer/issues/2152, and therefore had to be reverted https://github.com/livepeer/go-livepeer/pull/2163.

**Specific updates (required)**

- Add `TransactOpts` to the `Client` struct
- Make all bonding contracts use `TransactOpts` from `Client` instead of the default one
- Add lock to guard any changes to `TransactOpts` in `Client`
- Update replace logic in `transactionManager` to cover legacy tx

**How did you test each of these updates (required)**

- Tested with [devtool](https://github.com/livepeer/go-livepeer/tree/master/cmd/devtool)
  - Check that transactions have `maxFeePerGas` set to the value defined by user `maxGasPrice`
  - Check that streams do not stop to be processed when `maxGasPrice` is set
  - Checl that if `maxGasPrice` is reset (set to `0`), then `maxFeePerGas` has the default value again
- Tested with Rinkeby
  - Sample transaction: https://rinkeby.etherscan.io/tx/0xe5f5e326e843e487acfb4a2ea1c6c93b9a70e08fb8c7e17104510b1588fa9356
- Tested max gas price with Arbitrum Rinkeby Testnet
  - Sample transaction: https://testnet.arbiscan.io/tx/0x5a5cbd9d807de5735ded121a6c8f92cfb403f9ff0d6729cfaf9bfac79da88858

I didn't test the transaction replacement in Arbitrum Rinkeby Testnet

**Does this pull request close any open issues?**

fix #2084
fix #2243

**Checklist:**

- [x] Read the [contribution guide](./doc/contributing.md)
- [x] `make` runs successfully
- [x] All tests in `./test.sh` pass
- [ ] README and other documentation updated
- [x] [Pending changelog](./CHANGELOG_PENDING.md) updated

### CODE REVIEW

**Review by yondonfu — CHANGES_REQUESTED** [review]
I think there may be a problem with this approach since the `client` struct currently [embeds each of the binding sessions](https://github.com/livepeer/go-livepeer/blob/c50c0ccf3cec22b4e10eb70d1103348ff2f5a751/eth/client.go#L135). As a result, if the caller invokes a method from a binding session that isn't explicitly defined on `client`, the method will be invoked on the underlying binding session that defines it [1].

For example, consider the method [LivepeerTokenSession.Transfer()](https://github.com/livepeer/go-livepeer/blob/c50c0ccf3cec22b4e10eb70d1103348ff2f5a751/eth/contracts/livepeerToken.go#L597). At the moment, `Transfer()` is not defined on `client`, so a call to `client.Transfer()` (such as the one [here](https://github.com/livepeer/go-livepeer/blob/c50c0ccf3cec22b4e10eb70d1103348ff2f5a751/server/webserver.go#L1049)) is equivalent to `client.LivepeerTokenSession.Transfer()`. With the current changes in this PR, that call should result in a nil pointer error because the `TransactOpts` filed in `LivepeerTokenSession` is not set.

I suggest thinking about a way to handle this case.

[1] https://go.dev/doc/effective_go#embedding

**Comment by leszko** [comment]
@yondonfu Good point! You're right that it can be very confusing because you'd always need to remember that you can only use functions that were overridden in the client.

I checked and you can't configure `abigen` to generate only `get` functions in the `session` objects. Another approach could be to not store `TransactOpts` in `client`, but to update each session with `TransactOpts` while calling `setTransactOpts()`. Something like this.

```golang
func (c *client) setTransactOpts(opts bind.TransactOpts) {
	c.transOptsMu.Lock()
	c.LivepeerTokenSession.TransactOpts = opts
	c.LivepeerTokenFaucetSession.TransactOpts = opts
	c.ServiceRegistrySession.TransactOpts = opts
	c.BondingManagerSession.TransactOpts = opts
	// ...
	c.transOptsMu.Unlock()
}
```

But I think it won't work because assignment operation is not thread-safe in Go and `TransactOpts` is used in other places in the auto-generated Go code.

Since I don't think you can embed structs partly in Go, then I think there is no better option than getting rid of embedding the sessions at all. It results in some boilerplate delegation functions, but at least it's pretty straightforward. I added this commit: https://github.com/livepeer/go-livepeer/pull/2171/commits/6cdba5ee52b445308b632338b722e23e07033d3c . Let me know if you see any better solution to it.

**Review by yondonfu — APPROVED** [review]
LGTM after resolving conflicts!

**Comment by yondonfu** [comment]
> Let me know if you see any better solution to it.

Hm don't see an immediate better solution. The extra boilerplate is not great, but can live with it for now!

**Comment by leszko** [comment]
I tried to test it in Arbitrum Testnet and got the following message, which I guess is a blocker for this PR.

```
maxFeePerGas or maxPriorityFeePerGas specified but london is not active yet
```

**Review by yondonfu — APPROVED** [review]
LGTM. Let's update the changelog entry to reflect that this PR also make updates to be compatible with Arbitrum.

**Pull request merged**
