### PR TITLE
update ports to be different for B / O / T

### PR DESCRIPTION
**Pull request by ad-astra-video**
**What does this pull request do? Explain your changes. (required)**
Updates ports as suggested in [#2797](https://github.com/livepeer/go-livepeer/issues/2797#issue-1718155191)

@chrishobcroft 

**Specific updates (required)**
- updated `starter.go` to use separate ports

**How did you test each of these updates (required)**
- ran test.sh and `starter.go` tests passed

**Does this pull request close any open issues?**
See above.

**Checklist:**

- [ ] Read the [contribution guide](./doc/contributing.md)
- [X] `make` runs successfully
- [ ] All tests in `./test.sh` pass  I think the test that is failing is not caused by this update but please confirm.
- [ ] README and other documentation updated
- [ ] [Pending changelog](./CHANGELOG_PENDING.md) updated

### CODE REVIEW

**Review by leszko — CHANGES_REQUESTED** [review]
The PR looks good, but I see that e2e tests are failing.

```
E0831 13:58:06.488086   20826 gaspricemonitor.go:122] error getting gas price: Post "http://172.17.0.1:32779/": read tcp 172.18.0.2:39278->172.17.0.1:32779: read: connection reset by peer
E0831 13:58:06.661925   20826 webserver.go:22] http: Server closed
FAIL
FAIL	github.com/livepeer/go-livepeer/test/e2e	326.824s
FAIL
Error: Process completed with exit code 1.
```

Could you please check?

**Comment by ad-astra-video** [comment]
Can you try re-running the test? I think the one that is failing is one of the problem tests.  The tests pass on my test run but had to run twice.

https://github.com/ad-astra-video/go-livepeer/actions/runs/6084402253

**Comment by leszko** [comment]
> Can you try re-running the test? I think the one that is failing is one of the problem tests. The tests pass on my test run but had to run twice.
> 
> https://github.com/ad-astra-video/go-livepeer/actions/runs/6084402253

Yeah, that's possible. I think that you need to resolve the conflicts and then when you push the build should pass.

**Comment by ad-astra-video** [comment]
> > Can you try re-running the test? I think the one that is failing is one of the problem tests. The tests pass on my test run but had to run twice.
> > https://github.com/ad-astra-video/go-livepeer/actions/runs/6084402253
> 
> Yeah, that's possible. I think that you need to resolve the conflicts and then when you push the build should pass.

These conflicts are the changes I made for the ports right? Am I missing something?

**Review by leszko — APPROVED** [review]

**Comment by eliteprox** [comment]
Good work, this will make running the full stack much easier on a single machine.

**Comment by chrishobcroft** [comment]
Thank you @ad-astra-video this works nicely!

**Pull request merged**
