### PR TITLE
server: webserver pricing specific endpoints for bcast max price and orchestrator base price

### PR DESCRIPTION
**Pull request by kyriediculous**
**What does this pull request do? Explain your changes. (required)**

Add price specific setter endpoints to the webserver  

**Specific updates (required)**
- created new handler `/setBroadcastMaxPrice`
- created new handler `/setOrchestratorPrice`

**How did you test each of these updates (required)**

**Checklist:**
- [ ] README and other documentation updated
- [x] Node runs in OSX and devenv
- [x] All tests in `./test.sh` pass

### CODE REVIEW

**Review by yondonfu — COMMENTED** [review]
While I understand that having a standalone price setter makes it convenient to *just* programatically set the price,  I wonder if an alternative could be to modify the `/setBroadcastConfig` and `/setOrchestratorConfig` endpoints to allow for certain params to be omitted so that node state is only updated for the provided params? In this case, if the only params provided to a `/setBroadcastConfig` request are `pricePerUnit` and `pixelsPerUnit`, only a price update is executed and other state updates are skipped. And in the case where no params are provided, an error could be returned indicating that no params were provided. I bring this up because we might want to allow other config options to be set during run time such as the ticket EV and I'm a bit wary of adding new endpoints for each new config option - curious what you think.

**Comment by kyriediculous** [comment]
If you think it's worth the engineering  effort to do this properly _right now_  considering it's not on the critical path (the project for which this is a requirement is an untested, unofficial tool for now).

**Comment by yondonfu** [comment]
Thanks for the clarification on what this feature is needed for.

Given that the external tool that depends on this feature is still being iterated on, I don't see a need to rush this feature (it is also missing tests) in if there might be a better way to implement it. Let's think about what we believe is the "proper" way to implement this feature and then we can work on merging it in.

**Comment by kyriediculous** [comment]
closed in favor of https://github.com/livepeer/go-livepeer/pull/1597

**Pull request closed without merging**
